# Generated by Django 3.1.7 on 2021-03-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
